<div class="content-wrap">
	<div class="flexbox flex-column">
		<div class="flex--1 font-white">
			<h2 class="section-heading">Facilities</h2>
			<h3 class="subheading"> Creative & social design with high tech facilities</h3>
			<p class="larger-text"> The EIBC has been purpose built for <strong>you</strong>. Through your collaborative intent and through the collegial atmosphere generated by innovative thinking and open discussion, <strong>you</strong> will be energised by your peers, the EIBC’s partners and their broader community.</p>
			<div class="clear-small"></div>
			<div class="image-mood-board">
				<div class="mood-piece">
					<div class="back" id="facilities-image-6"></div>
					<div class="content">
						<div class="content-wrap">
							<p class="larger-text">EIBC at dusk</p>
						</div>
					</div>
				</div>
				<div class="mood-piece">
					<div class="back" id="facilities-image-1"></div>
					<div class="content">
						<div class="content-wrap">
							<p class="larger-text">Meeting room in Dynamic area</p>
						</div>
					</div>
				</div>
				<div class="mood-piece smaller">
					<div class="back" id="facilities-image-2"></div>
					<div class="content">
						<div class="content-wrap">
							<p class="larger-text">Fully equipped kitchen area</p>
						</div>
					</div>
				</div>
				<div class="mood-piece">
					<div class="back" id="facilities-image-3"></div>
					<div class="content">
						<div class="content-wrap">
							<p class="larger-text">Hot Desks in Active area</p>
						</div>
					</div>
				</div>
				<div class="mood-piece larger">
					<div class="back" id="facilities-image-4"></div>
					<div class="content">
						<div class="content-wrap">
							<p class="larger-text">A meeting pod</p>
						</div>
					</div>
				</div>
				<div class="mood-piece">
					<div class="back" id="facilities-image-5"></div>
					<div class="content">
						<div class="content-wrap">
							<p class="larger-text">BBQ area is free for the public to use</p>
						</div>
					</div>
				</div>
			</div>
			<div class="clear-small"></div>
			<div class="active-show-hide h postcard back-dark-grey facilities-information">
				<div class="flexbox">
					<div class="flex--1">
						<h4 class="subheading">Business Facilities</h4>
						<p class="default-text">
							The EIBC is designed with innovators in mind, especially in the technological domain. The building is fully networked, with high speed fibre, cloud collaboration, video conferencing, advanced security and presentation facilities.
							<br><br>
							It is an interactive design that encourages social interaction by providing a work/play balance in its spaces.
							<br><br>
							This space is designed around a flexible platform of active and dynamic zones that accommodate a changing world and workplace. Your ‘office space’ can expand and contract according to your needs.
						</p>
					</div>
					<div class="flex--1">
						<h4 class="subheading">Environmental Facilities</h4>
						<p class="default-text">
							Most importantly, the EIBC is a melting pot of thought leadership that sees the coming together of start-ups, industry partners, government bodies and tertiary institutions in a vibrant ecosystem. Quite literally, the EIBC is founded on a commitment to the environment. Underneath the facility sits a highly advanced bio filtration system for locally collected stormwater, which feeds the building’s greywater use as well as a large filtration pond and most of the facilities plants and grasses.
							<br><br>
							The building itself is surrounded by green walls, and features the latest in built-form sustainability in terms of natural light and heat, air flow, and energy conservation. It’s an innovative, growing facility to grow innovative ideas.
						</p>
					</div>
				</div>
				<h2 class="section-heading">Research at EIBC</h2>
				<div class="flexbox">
					<div class="flex--1">
						<h4 class="subheading">Dry Labs</h4>
						<p class="default-text">
							The EIBC is designed with innovators in mind, especially in the technological domain. The building is fully networked, with high speed fibre, cloud collaboration, video conferencing, advanced security and presentation facilities.
							<br><br>
							It is an interactive design that encourages social interaction by providing a work/play balance in its spaces.
							<br><br>
							This space is designed around a flexible platform of active and dynamic zones that accommodate a changing world and workplace. Your ‘office space’ can expand and contract according to your needs.
						</p>
					</div>
					<div class="flex--1">
						<h4 class="subheading">Wet labs</h4>
						<p class="default-text">
							Most importantly, the EIBC is a melting pot of thought leadership that sees the coming together of start-ups, industry partners, government bodies and tertiary institutions in a vibrant ecosystem. Quite literally, the EIBC is founded on a commitment to the environment. Underneath the facility sits a highly advanced bio filtration system for locally collected stormwater, which feeds the building’s greywater use as well as a large filtration pond and most of the facilities plants and grasses.
						</p>
					</div>
				</div>
				<div class="clear-small"></div>
				<a class="btn btn-normal class-toggler" data-toggle-class="h" data-target=".facilities-information">Show Less</a>
			</div>
			<a class="btn btn-white active-show-hide class-toggler facilities-information" data-toggle-class="h" data-target=".facilities-information">Learn More</a>
		</div>
</div>